# Change these first
owner: sendhelper # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Sendhelper
    url: https://www.sendhelper.com
