# Change these first
owner: sendhelper # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Sendhelper
    url: https://www.sendhelper.com
status-website:
# baseUrl: /uptime
  cname: status.sendhelper.com
  name: Sendhelper
i18n:
  footer: © Sendtech Pte Ltd 2022 | All rights reserved
