# Change these first
owner: sendhelper # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Sendhelper
    url: https://www.sendhelper.com

status-website:
  baseUrl: /sendhelper/uptime
  logoUrl: https://www.sendhelper.com/static/images/logo.png
  name: Sendhelper
  introTitle: "Sendhelper Status."
  introMessage: This is a Sendhelper status page which uses **real-time** data from our website
